### ISSUE TITLE
Help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [Grima04/mesa-turnip-kgsl#2]
![Screenshot_2022-07-13-09-04-36-817_com termux](https://user-images.githubusercontent.com/72664192/178645150-88ef943b-1613-4278-a7c9-45026006f643.jpg)

**Comment by Saikatsaha1996** [comment]
> ![Screenshot_2022-07-13-09-04-36-817_com termux](https://user-images.githubusercontent.com/72664192/178645150-88ef943b-1613-4278-a7c9-45026006f643.jpg)

**Comment by Saikatsaha1996** [comment]
@Grima04 i don't know.. i build successfully.. but when i installed in Exagear.. directx not opening, GPU Caps viewer not opening.. nothing work with GPU..

:/

**Comment by Mizumo-prjkt** [comment]
you need to install x11 devel binaries first
